<script setup>
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { activeServer } from '../stores/serverStore.js'
import { usePageMeta } from '../composables/usePageMeta.js'

const { t, locale } = useI18n()

// Prefer a Russian description when the UI is in Russian, falling back to the
// mod's original (English) metadata description.
function descOf(m) {
  if (locale.value === 'ru' && m.description_ru) return m.description_ru
  return m.description || ''
}

// Per-server mod list generated by scripts/generate_mods_list.py into
// public/mods/<slug>.json. Loaded lazily; a 404 just means no list for this server.
const mods = ref([])
const loaded = ref(false)
const query = ref('')

async function loadMods(slug) {
  mods.value = []
  loaded.value = false
  if (!slug) return
  try {
    const res = await fetch(`/mods/${encodeURIComponent(slug)}.json`)
    if (res.ok) {
      const data = await res.json()
      mods.value = Array.isArray(data) ? data : []
    }
  } catch {
    mods.value = []
  } finally {
    loaded.value = true
  }
}

const serverName = computed(() => activeServer.value?.name || '')

const filtered = computed(() => {
  const q = query.value.trim().toLowerCase()
  if (!q) return mods.value
  return mods.value.filter(
    (m) =>
      m.name?.toLowerCase().includes(q) ||
      m.id?.toLowerCase().includes(q) ||
      m.description?.toLowerCase().includes(q) ||
      m.description_ru?.toLowerCase().includes(q),
  )
})

watch(
  () => activeServer.value?.slug,
  (slug) => {
    query.value = ''
    loadMods(slug)
  },
  { immediate: true },
)

usePageMeta({
  title: t('serverGuide.modsTitle'),
  description: t('serverGuide.modsSubtitle'),
  url: 'https://void-rp.ru/mods',
  breadcrumbs: [
    { name: t('nav.home'), url: '/' },
    { name: t('serverGuide.modsTitle') },
  ],
})
</script>

<template>
  <section class="gp py-3 md:py-4">
    <div class="container-shell max-w-[1240px] space-y-3">

      <!-- Header -->
      <header class="gp-header">
        <div class="gp-header__left">
          <p class="gp-eyebrow">{{ t('serverGuide.tabMods') }}<span v-if="serverName"> · {{ serverName }}</span></p>
          <h1 class="gp-h1">{{ t('serverGuide.modsTitle') }}</h1>
          <p class="gp-desc">{{ t('serverGuide.modsSubtitle') }}</p>
        </div>
      </header>

      <!-- Empty (no list for this server) -->
      <div v-if="loaded && mods.length === 0" class="surface-card sg-empty">
        <div class="sg-empty__icon">🧩</div>
        <h2 class="sg-empty__title">{{ t('serverGuide.emptyTitle') }}</h2>
        <p class="sg-empty__text">{{ t('serverGuide.emptyText') }}</p>
      </div>

      <template v-else>
        <div class="sg-mods__bar surface-card">
          <input
            v-model="query"
            type="search"
            class="sg-mods__search"
            :placeholder="t('serverGuide.modsSearch')"
          />
          <span class="sg-mods__count">{{ t('serverGuide.modsCount', { shown: filtered.length, total: mods.length }) }}</span>
        </div>

        <div v-if="filtered.length === 0" class="surface-card sg-mods__empty">
          {{ t('serverGuide.modsEmpty') }}
        </div>

        <div v-else class="sg-mods__grid">
          <article v-for="m in filtered" :key="m.id" class="surface-card sg-mod">
            <div class="sg-mod__head">
              <h3 class="sg-mod__name">{{ m.name }}</h3>
              <span v-if="m.version" class="sg-mod__ver">{{ m.version }}</span>
            </div>
            <p class="sg-mod__desc" :class="{ 'sg-mod__desc--muted': !descOf(m) }">
              {{ descOf(m) || t('serverGuide.modsNoDesc') }}
            </p>
            <code class="sg-mod__id">{{ m.id }}</code>
          </article>
        </div>
      </template>

    </div>
  </section>
</template>

<style scoped>
.gp-header { display: grid; gap: 1rem; align-items: start; }
.gp-eyebrow {
  font-size: .75rem; font-weight: 700; letter-spacing: .18em; text-transform: uppercase;
  color: rgb(100 116 139); margin: 0 0 .3rem;
}
.gp-h1 { font-size: 1.5rem; font-weight: 900; color: #f8fbff; margin: 0 0 .4rem; letter-spacing: -.03em; }
.gp-desc { font-size: .83rem; line-height: 1.6; color: rgb(100 116 139); margin: 0; max-width: 560px; }

.sg-mods__bar {
  display: flex; align-items: center; gap: .75rem; flex-wrap: wrap;
  padding: .6rem .8rem; position: sticky; top: 4.75rem; z-index: 5;
}
.sg-mods__search {
  flex: 1; min-width: 180px; padding: .5rem .75rem; border-radius: 9px;
  background: rgba(0,0,0,.28); border: 1px solid rgba(255,255,255,.1);
  color: #f0f4ff; font-size: .85rem;
}
.sg-mods__search:focus { outline: none; border-color: rgba(134,239,172,.45); }
.sg-mods__count { font-size: .76rem; color: rgb(100 116 139); white-space: nowrap; }
.sg-mods__empty { text-align: center; padding: 2.5rem 1rem; color: rgb(100 116 139); font-size: .85rem; }
.sg-mods__grid {
  display: grid; gap: .55rem;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
}
.sg-mod { padding: .75rem .85rem; display: flex; flex-direction: column; gap: .3rem; }
.sg-mod__head { display: flex; align-items: baseline; justify-content: space-between; gap: .5rem; }
.sg-mod__name { font-size: .88rem; font-weight: 800; color: #f0f4ff; margin: 0; line-height: 1.25; }
.sg-mod__ver {
  flex-shrink: 0; font-size: .66rem; font-weight: 700; color: rgb(100 116 139);
  font-variant-numeric: tabular-nums; font-family: ui-monospace, monospace;
}
.sg-mod__desc { font-size: .78rem; line-height: 1.5; color: rgb(148 163 184); margin: 0; }
.sg-mod__desc--muted { color: rgb(100 116 139); font-style: italic; }
.sg-mod__id {
  align-self: flex-start; font-family: ui-monospace, monospace; font-size: .68rem;
  color: rgb(110 231 183); background: rgba(0,0,0,.28); padding: .08rem .35rem; border-radius: 5px;
}

.sg-empty { text-align: center; padding: 3.5rem 1rem; }
.sg-empty__icon { font-size: 2.6rem; margin-bottom: .8rem; }
.sg-empty__title { font-size: 1.3rem; font-weight: 900; color: #f0f4ff; margin-bottom: .4rem; }
.sg-empty__text { color: rgb(100 116 139); font-size: .85rem; }
</style>
